sudo: required
services:
  - docker
before_install:
  - docker build -t arpitpriv/docker-web:latest -f web/Dockerfile.dev ./web
script:
  - docker run -e CI=true arpitpriv/docker-web:latest npm run test -- --coverage

# s3 error is still there check
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learninh-docker-temp"
  env: "LearninhDockerTemp-env"
  bucket_name: "elasticbeanstalk-us-east-2-943977056781"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESSS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
