sudo: required
services:
  - docker
before_install:
  - docker build -t arpitpriv/docker-web:latest -f web/Dockerfile.dev ./web
script:
  - docker run arpitpriv/docker-web:latest npm run test --coverage
