version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./web:/app
    stdin_open: true
  test:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    command: ["npm", "run", "test"]
    stdin_open: true
